config/routes.rb
Rails.application.routes.draw do
  devise_for :owners

  root 'restaurants#index'

  resources :restaurants

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
            @restaurant = Restaurant.find(params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        if @restaurant.save
            flash[:notice] = 'your restaurant was created'
            redirect_to @restaurant
         else
             render action: 'new'
         end
    end

    def edit
        @restaurant = Restaurant.find(params[:id])
    end

    def update
        @restaurant = Restaurant.find(params[:id])
        if @restaurant.update_attributes(restaurant_params)
            flash[:notice] = 'Your restaurant was updated'
            redirect_to @restaurant
        else
            render action: 'new'
        end
    end

    def destroy
        @restaurant = Restaurant.find(params[:id])
        @restaurant.destroy

        redirect_to @restaurant
    end

    private
        def restaurant_params
            params.require(:restaurant).permit(:id, :name, :address, :phone, :description)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>Address: <%= f.text_field :address %></p>
    <p>Phone number: <%= f.text_field :phone %></p>
    <p>Description: <%= f.text_field :description %></p>
    <p><%= f.submit "Add/Update this Restaurant"%></p>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants<h1>
<table>
  <thread>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thread>
  <h3><%= link_to 'New', new_restaurant_path %></h3>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
      <td><%= link_to 'Edit', restaurant_path(restaurant) %></td>
      <td><%= link_to 'Delete', restaurant_path(restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>Address: <%= f.text_field :address %></p>
    <p>Phone number: <%= f.text_field :phone %></p>
    <p>Description: <%= f.text_field :description %></p>
    <p><%= f.submit "Add/Update this Restaurant"%></p>
<% end %>

app/views/restaurants/show.html.erb
<p>Name: <%= @restaurant.name %>
<p>Description: <%= @restaurant.description %>
<p>Address: <%= @restaurant.address %>
<p>Phone: <%= @restaurant.phone %>

<p> <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<p> <%= link_to "Back", restaurants_path %>